### ISSUE TITLE
Compilation Failed

### ISSUE THREAD

**Issue by vanhauser-thc** [jaiverma/joern-queries#1]
fyi I stumbled on your blog and github repo when playing around with joern - and got this error:
```
joern> def getFlows(methodName: String) : Unit = {
           val candidateFuncs = cpg.method.name(methodName)
               .caller
               .l
               .filter(func => {
                   val src = func.start.parameter
                   val sink = func.start.methodReturn
                   sink.reachableBy(src)
               }.size > 0)
               .start
               .name
               .l
           for (f <- candidateFuncs) {
               val src = cpg.call.name(f)
               val sink = cpg.call.name("memcpy").argument
               if (src.size > 0) {
                   if (sink.reachableBy(src).size > 0) {
                       print(sink.reachableByFlows(src).p)
                   }
                   else {
                       getFlows(f)
                   }
               }
               else {
                   return
               }
           }
       } 
cmd12.sc:10: value start is not a member of List[io.shiftleft.codepropertygraph.generated.nodes.Method]
possible cause: maybe a semicolon is missing before `value start`?
        .start
         ^
Compilation Failed
```
likely the api has changed.

**Comment by jaiverma** [comment]
Thanks for creating the issue. Yes there was an API change (https://docs.joern.io/upgrade-guides/).
I'll keep this issue open and update the code to work with the new API.

I think my code works with API prior to `v1.1.0`. Therefore it should work with https://github.com/ShiftLeftSecurity/joern/releases/tag/v1.0.187 and earlier releases.

**Comment by jaiverma** [comment]
Updated the blog posts [here](https://jaiverma.github.io/blog/joern-intro) and [here](https://jaiverma.github.io/blog/joern-uboot), and the queries to work with the newer API. Also, now Joern supports inter-procedural data-flow analysis as well so that is super cool.
